# -*- coding: utf-8 -*-
"""
/***************************************************************************
 thebestrestaurant
                                 A QGIS plugin
 this plugin finds the best restaurant
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-27
        copyright            : (C) 2018 by waleed
        email                : waleedk745@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load thebestrestaurant class from file thebestrestaurant.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .the_best_restaurant import thebestrestaurant
    return thebestrestaurant(iface)
